apiVersion: v1
kind: Service
metadata:
  name: web-service-nodeport
spec:
  type: NodePort
  selector:
    app: web-nodeport
  ports:
    - protocol: TCP
      port: 80          # Service VIP port
      targetPort: 80    # Pod containerPort
      nodePort: 30080   # Port opened on EVERY node (30000-32767)
