apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-pending
spec:
  containers:
    - name: app
      image: nginx:1.25-alpine
      resources:
        requests:
          memory: "512Gi"
          cpu: "100"
