apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-html-green
data:
  index.html: |
    <html><body><h1>myapp</h1><p>GREEN ENVIRONMENT - v2</p></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      slot: green
  template:
    metadata:
      labels:
        app: myapp
        slot: green
        version: v2
    spec:
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: myapp-html-green
