apiVersion: v1
kind: ConfigMap
metadata:
  name: recreate-html-v2
data:
  index.html: |
    <html><body><p>VERSION: v2 (UPGRADED)</p></body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-recreate
  template:
    metadata:
      labels:
        app: app-recreate
        version: v2
    spec:
      containers:
        - name: web
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: recreate-html-v2
