apiVersion: v1
kind: Secret
metadata:
  name: yatri-db-secret
type: Opaque
data:
  # echo -n 'yatri_admin'    | base64  ->  eWF0cmlfYWRtaW4=
  # echo -n 'secretpassword' | base64  ->  c2VjcmV0cGFzc3dvcmQ=
  POSTGRES_USER: eWF0cmlfYWRtaW4=
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ=
